[package]
name = "gosub_v8"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_shared = { path = "../gosub_shared" }
gosub_webexecutor = { path = "../gosub_webexecutor" }
thiserror = "2.0.7"
v8 = "130.0.1"
anyhow = "1.0.94"
serde_json = "1.0.133"