[package]
name = "gosub_renderer"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_rendering = { path = "../gosub_render_utils" }
gosub_shared = { path = "../gosub_shared" }
gosub_net = { path = "../gosub_net" }
anyhow = "1.0.94"
image = "0.25.5"
url = "2.5.4"
log = "0.4.22"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.47"
web-sys = "0.3.72"
